### ISSUE TITLE
Add a new file format: ASDF (Roman) as input source catalog.

### ISSUE THREAD

**Issue by sshen-stsci** [astronomy-commons/hats-import#433]
**Feature request**
Support ASDF file format

**Before submitting**
Please check the following:

Roman source catalog will be generated with ASDF file format. It would be very helpful to have HATS to support ASDF file format in addition to parquet file format. We plan to use HATS to perform Roman catalog spatial search.

Related links:
https://github.com/asdf-format/asdf
https://github.com/asdf-format/tutorials

**Comment by delucchi-cmu** [comment]
Sharon provided several ASDF example files (privately), and we were able to import them into HATS, using the above `asdf_reader.py` extension.
